package com.example.whatsinmyfridge.core.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * "Warmes Bistro" - gedecktes Terracotta/Rost (Primär), Bernstein/Senf (Sekundär)
 * und gedeckte Himbeere (Tertiär). Kein Grün, bewusst gedeckter/ruhiger als die
 * übrigen Warmton-Themes, damit es "clean" statt laut wirkt.
 */
internal val FridgeLightColors = lightColorScheme(
    primary = Color(0xFFB8472B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBCB),
    onPrimaryContainer = Color(0xFF3A0900),
    secondary = Color(0xFF9C6B00),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDEA6),
    onSecondaryContainer = Color(0xFF2B1800),
    tertiary = Color(0xFFA23E5B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E1),
    onTertiaryContainer = Color(0xFF3F0011),
    background = Color(0xFFFFF9F5),
    onBackground = Color(0xFF241A14),
    surface = Color(0xFFFFF9F5),
    onSurface = Color(0xFF241A14),
    surfaceVariant = Color(0xFFEDE0D8),
    onSurfaceVariant = Color(0xFF52443C),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF3ED),
    surfaceContainer = Color(0xFFF9ECE3),
    surfaceContainerHigh = Color(0xFFF3E4D8),
    surfaceContainerHighest = Color(0xFFEDDCCC),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF8A7A70),
    outlineVariant = Color(0xFFDBC8BB),
)

/** "Warmes Bistro bei Nacht" - dieselbe Rost/Bernstein/Himbeere-Familie, warm statt kühl-schwarz. */
internal val FridgeDarkColors = darkColorScheme(
    primary = Color(0xFFFFB59C),
    onPrimary = Color(0xFF5C1A00),
    primaryContainer = Color(0xFF7C2D0F),
    onPrimaryContainer = Color(0xFFFFDBCB),
    secondary = Color(0xFFF0C060),
    onSecondary = Color(0xFF422D00),
    secondaryContainer = Color(0xFF614300),
    onSecondaryContainer = Color(0xFFFFDEA6),
    tertiary = Color(0xFFFFB0C4),
    onTertiary = Color(0xFF5E1123),
    tertiaryContainer = Color(0xFF7D2938),
    onTertiaryContainer = Color(0xFFFFD9E1),
    background = Color(0xFF1A1310),
    onBackground = Color(0xFFF0E2D9),
    surface = Color(0xFF1A1310),
    onSurface = Color(0xFFF0E2D9),
    surfaceVariant = Color(0xFF52443C),
    onSurfaceVariant = Color(0xFFD8C7BB),
    surfaceContainerLowest = Color(0xFF120D0A),
    surfaceContainerLow = Color(0xFF211812),
    surfaceContainer = Color(0xFF271D16),
    surfaceContainerHigh = Color(0xFF33251C),
    surfaceContainerHighest = Color(0xFF3E2C21),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFFA08A7D),
    outlineVariant = Color(0xFF52443C),
)

/** "Verspielt" - gesättigte Mandarine, knalliges Pink und Sonnenblumengelb. Der lauteste Modus. */
internal val FridgePlayfulColors = lightColorScheme(
    primary = Color(0xFFE8590C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBC4),
    onPrimaryContainer = Color(0xFF331100),
    secondary = Color(0xFFE0186B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD6E6),
    onSecondaryContainer = Color(0xFF3D0021),
    tertiary = Color(0xFFE0B400),
    onTertiary = Color(0xFF3A2E00),
    tertiaryContainer = Color(0xFFFFE897),
    onTertiaryContainer = Color(0xFF241A00),
    background = Color(0xFFFFF8F1),
    onBackground = Color(0xFF2A1C10),
    surface = Color(0xFFFFF8F1),
    onSurface = Color(0xFF2A1C10),
    surfaceVariant = Color(0xFFF1DFC9),
    onSurfaceVariant = Color(0xFF52443A),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1E2),
    surfaceContainer = Color(0xFFFCE9D3),
    surfaceContainerHigh = Color(0xFFF6E1C6),
    surfaceContainerHighest = Color(0xFFF0D9B9),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF8A7761),
    outlineVariant = Color(0xFFDBC7AA),
)

/** "Sonnenuntergang" - Korallrot, Brandorange, Gold. Wie ein Abendhimmel. */
internal val FridgeSunsetColors = lightColorScheme(
    primary = Color(0xFFD8402A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9CE),
    onPrimaryContainer = Color(0xFF410900),
    secondary = Color(0xFFE07A00),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDDB8),
    onSecondaryContainer = Color(0xFF2C1600),
    tertiary = Color(0xFFC9A227),
    onTertiary = Color(0xFF3A2E00),
    tertiaryContainer = Color(0xFFFFEEB0),
    onTertiaryContainer = Color(0xFF241A00),
    background = Color(0xFFFFF6F0),
    onBackground = Color(0xFF2A1712),
    surface = Color(0xFFFFF6F0),
    onSurface = Color(0xFF2A1712),
    surfaceVariant = Color(0xFFF0DDD1),
    onSurfaceVariant = Color(0xFF52443C),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDEEE4),
    surfaceContainer = Color(0xFFF9E4D5),
    surfaceContainerHigh = Color(0xFFF3D8C4),
    surfaceContainerHighest = Color(0xFFEDCBB0),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF8A7062),
    outlineVariant = Color(0xFFDBC0AE),
)

/** "Beere" - dunkles Beeren-Magenta, Himbeer-Rosa, warmes Bronzegold. Edler, juwelenartiger Look. */
internal val FridgeBerryColors = lightColorScheme(
    primary = Color(0xFF8E2255),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD8E7),
    onPrimaryContainer = Color(0xFF3A0020),
    secondary = Color(0xFFB23A55),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9DE),
    onSecondaryContainer = Color(0xFF400010),
    tertiary = Color(0xFFA6741C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFE1A6),
    onTertiaryContainer = Color(0xFF2B1D00),
    background = Color(0xFFFFF7FA),
    onBackground = Color(0xFF2B1720),
    surface = Color(0xFFFFF7FA),
    onSurface = Color(0xFF2B1720),
    surfaceVariant = Color(0xFFEEDCE3),
    onSurfaceVariant = Color(0xFF4F4048),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDEFF3),
    surfaceContainer = Color(0xFFF9E4EB),
    surfaceContainerHigh = Color(0xFFF3D8E1),
    surfaceContainerHighest = Color(0xFFEDCBD8),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF806772),
    outlineVariant = Color(0xFFD8BFC9),
)

/**
 * "Salbei" - der grüne Vertreter im Set: gedecktes Salbei-/Waldgrün als Primär,
 * warmes Oliv-Bronze als Sekundär und ein Terracotta-Akzent als Tertiär, damit es
 * trotz Grün-Basis warm und "bunt" statt kühl-klinisch wirkt.
 */
internal val FridgeSageColors = lightColorScheme(
    primary = Color(0xFF4B6B4E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC8ECC7),
    onPrimaryContainer = Color(0xFF002106),
    secondary = Color(0xFF8A6D3B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF0E0B8),
    onSecondaryContainer = Color(0xFF2B1D00),
    tertiary = Color(0xFFB8574A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDAD1),
    onTertiaryContainer = Color(0xFF410900),
    background = Color(0xFFF5FAF3),
    onBackground = Color(0xFF191E17),
    surface = Color(0xFFF5FAF3),
    onSurface = Color(0xFF191E17),
    surfaceVariant = Color(0xFFDEE5D9),
    onSurfaceVariant = Color(0xFF424940),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEEF5EA),
    surfaceContainer = Color(0xFFE7F0E2),
    surfaceContainerHigh = Color(0xFFE0E9DA),
    surfaceContainerHighest = Color(0xFFD9E2D2),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF72796C),
    outlineVariant = Color(0xFFC2CBBB),
)

/** "Granatapfel" - tiefes Weinrot, Rosé, antikes Gold. Edel und satt. */
internal val FridgePomegranateColors = lightColorScheme(
    primary = Color(0xFF9B1B30),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9DC),
    onPrimaryContainer = Color(0xFF40000A),
    secondary = Color(0xFFC0577A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E5),
    onSecondaryContainer = Color(0xFF3D0021),
    tertiary = Color(0xFFB08830),
    onTertiary = Color(0xFF3A2A00),
    tertiaryContainer = Color(0xFFFFE7B8),
    onTertiaryContainer = Color(0xFF2B1D00),
    background = Color(0xFFFFF7F5),
    onBackground = Color(0xFF2B1416),
    surface = Color(0xFFFFF7F5),
    onSurface = Color(0xFF2B1416),
    surfaceVariant = Color(0xFFEEDBDA),
    onSurfaceVariant = Color(0xFF4F4241),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDEFEE),
    surfaceContainer = Color(0xFFF9E3E2),
    surfaceContainerHigh = Color(0xFFF3D7D5),
    surfaceContainerHighest = Color(0xFFEDCAC8),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF8A7473),
    outlineVariant = Color(0xFFD8C1BF),
)

/** "Zitrus" - sonniges Gelb-Orange, komplett ohne Grün. Frühstücks-/Brunch-Stimmung. */
internal val FridgeCitrusColors = lightColorScheme(
    primary = Color(0xFFE0A100),
    onPrimary = Color(0xFF3A2A00),
    primaryContainer = Color(0xFFFFEBB0),
    onPrimaryContainer = Color(0xFF241A00),
    secondary = Color(0xFFE8590C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBC4),
    onSecondaryContainer = Color(0xFF331100),
    tertiary = Color(0xFFC77D00),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDFA6),
    onTertiaryContainer = Color(0xFF2B1C00),
    background = Color(0xFFFFFBF0),
    onBackground = Color(0xFF2A2205),
    surface = Color(0xFFFFFBF0),
    onSurface = Color(0xFF2A2205),
    surfaceVariant = Color(0xFFF0E4C4),
    onSurfaceVariant = Color(0xFF514736),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF5DF),
    surfaceContainer = Color(0xFFFAEECB),
    surfaceContainerHigh = Color(0xFFF4E5B4),
    surfaceContainerHighest = Color(0xFFEEDA9C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF8C7D57),
    outlineVariant = Color(0xFFDECDA0),
)

/** "Mitternacht" - edler Wein-Dunkelmodus: Rosé-Glow, Gold, Kupfer auf tiefem Bordeaux-Schwarz. */
internal val FridgeMidnightColors = darkColorScheme(
    primary = Color(0xFFFF8FA3),
    onPrimary = Color(0xFF5C0016),
    primaryContainer = Color(0xFF7D1B33),
    onPrimaryContainer = Color(0xFFFFD9DE),
    secondary = Color(0xFFE8B84B),
    onSecondary = Color(0xFF3F2D00),
    secondaryContainer = Color(0xFF5C4300),
    onSecondaryContainer = Color(0xFFFFE39B),
    tertiary = Color(0xFFD68A5C),
    onTertiary = Color(0xFF3D1D0A),
    tertiaryContainer = Color(0xFF5C3419),
    onTertiaryContainer = Color(0xFFFFDBC4),
    background = Color(0xFF170D12),
    onBackground = Color(0xFFF0DEE2),
    surface = Color(0xFF170D12),
    onSurface = Color(0xFFF0DEE2),
    surfaceVariant = Color(0xFF4A3038),
    onSurfaceVariant = Color(0xFFD6C0C6),
    surfaceContainerLowest = Color(0xFF0F080B),
    surfaceContainerLow = Color(0xFF1F1319),
    surfaceContainer = Color(0xFF25161D),
    surfaceContainerHigh = Color(0xFF302029),
    surfaceContainerHighest = Color(0xFF3B2933),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9C838B),
    outlineVariant = Color(0xFF4A3038),
)

/**
 * "Kontrast" - plakativ statt gedeckt: reinweißer Untergrund, fast schwarzer Text und drei
 * satte, klar getrennte Akzentfarben (Kobaltblau, Magenta, Gold). Neutrale Grau-Rampen statt
 * der warm getönten Container-Stufen der übrigen Themes, damit er sich bewusst als der
 * kontrastreichste, grafischste Modus im Set abhebt.
 */
internal val FridgeKontrastColors = lightColorScheme(
    primary = Color(0xFF0047FF),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD9E1FF),
    onPrimaryContainer = Color(0xFF00174D),
    secondary = Color(0xFFE4007C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD7EA),
    onSecondaryContainer = Color(0xFF5C0033),
    tertiary = Color(0xFFC79300),
    onTertiary = Color(0xFF000000),
    tertiaryContainer = Color(0xFFFFEBA6),
    onTertiaryContainer = Color(0xFF241A00),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF0A0A0A),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF0A0A0A),
    surfaceVariant = Color(0xFFE6E6E6),
    onSurfaceVariant = Color(0xFF2E2E2E),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F5F5),
    surfaceContainer = Color(0xFFEDEDED),
    surfaceContainerHigh = Color(0xFFE2E2E2),
    surfaceContainerHighest = Color(0xFFD6D6D6),
    error = Color(0xFFE30000),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF4A4A4A),
    outlineVariant = Color(0xFFC2C2C2),
)

/** Kleiner, kontextfreier Farbausschnitt eines Themes - für Vorschau-Kacheln in der Theme-Auswahl. */
data class ThemeSwatch(
    val background: Color,
    val primary: Color,
    val secondary: Color,
    val tertiary: Color,
)

internal fun ColorScheme.toSwatch() = ThemeSwatch(
    background = background,
    primary = primary,
    secondary = secondary,
    tertiary = tertiary,
)
